name: Lint

on: push

jobs:
  wait:
    name: Wait
    runs-on: ubuntu-latest
    steps:
      - name: wait
        run: sleep 20s

  setup:
    needs: wait
    uses: msamsel/vue-start-app/.github/workflows/setup.yml@master

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Job ID
        run: echo '${{ github.run_id }} | ${{ github.run_number }} | ${{ github.run_attempt }}'

      # - name: Checkout
      #   uses: actions/checkout@v2

      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '16'

      - name: Restore cache
        id: restore-cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/*
          key: ${{ runner.os }}-${{ github.sha }}

      - name: List
        run: ls ${{ github.workspace }}
      

      # - name: Check if cache exists
      #   if: steps.restore-cache.outputs.cache-hit != 'true'
      #   run: exit 1

      - name: Run lintgg
        run: yarn lint
