name: Pull request

on: push

jobs:
  setup:
    uses: msamsel/vue-start-app/.github/workflows/setup.yml@master
  
  changes:
    name: Changes
    runs-on: ubuntu-latest
    outputs:
      linter: ${{ steps.filter.outputs.linter }}
      test: ${{ steps.filter.outputs.test }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            linter:
              - 'src/**'
            test:
              - '!(tests/**)'

  test:
    needs: [setup, changes]
    if: ${{ needs.changes.outputs.test == 'true' }}
    uses: msamsel/vue-start-app/.github/workflows/test.yml@master

  linter:
    needs: [setup, changes]
    if: ${{ needs.changes.outputs.linter == 'true' }}
    uses: msamsel/vue-start-app/.github/workflows/lint.yml@master

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/*
          key: ${{ runner.os }}-${{ github.sha }}

      - name: Build
        run: yarn build
      
      - name: Cache build
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/dist
          key: dist-${{ runner.os }}-${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/dist
          key: dist-${{ runner.os }}-${{ github.sha }}
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: dist
          target-folder: ${{ secrets.DEPLOY_KEY }}
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          repository-name: msamsel/vue-test


