name: Test

on:
  workflow_call:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Job ID
        run: echo '${{ github.run_id }} | ${{ github.run_number }} | ${{ github.run_attempt }}'

      # - name: Checkout
      #   uses: actions/checkout@v2

      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '16'

      - name: Restore cache
        id: restore-cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/*
          key: ${{ runner.os }}-${{ github.sha }}

      - name: List
        run: ls ${{ github.workspace }}
      

      # - name: Check if cache exists
      #   if: steps.restore-cache.outputs.cache-hit != 'true'
      #   run: exit 1

      - name: Run tests
        run: yarn test:unit
